### PR TITLE
test(evmstaking/types): add test cases for staking contract

### PR DESCRIPTION
**Pull request by zsystm**
Increased test coverage of [client/x/evmstaking/types/staking_contract.go](https://github.com/piplabs/story/blob/main/client/x/evmstaking/types/staking_contract.go) from 0% to 100%.

issue: https://github.com/piplabs/story/issues/64

### CODE REVIEW

**Review by jdubpark — APPROVED** [review]

**Review by limengformal — APPROVED** [review]

**Comment by limengformal** [comment]
@zsystm There are some linter errors. Can you help fix them?
https://github.com/piplabs/story/actions/runs/10620207885/job/29452072032?pr=56

**Comment by zsystm** [comment]
> @zsystm There are some linter errors. Can you help fix them? https://github.com/piplabs/story/actions/runs/10620207885/job/29452072032?pr=56

I have a discussion point regarding a lint error.

The lint suggests changing the package name of the test file from `types` to `types_test`. However, the methods being tested in this PR are private methods, so they must be in the same package to be tested.

Therefore, it seems we need to make these methods public. 
Would it be acceptable to change these methods to public in this PR?

**Comment by zsystm** [comment]
@limengformal 
Could you please help me get the verifypr CI to pass?

Currently, the error message says, `description doesn’t match regex,` but it doesn’t specify what the regex is, so I’m not sure how to modify it to pass the CI.

Could you let me know how I should change the PR description to ensure the verifypr passes?

**Comment by limengformal** [comment]
@zsystm verifypr CI failures are not important. Feel free to ignore them.

@zsystm for the lint errors, I prefer to not change the original code. You may escape the lint check for those lines so linter can ignore them.

**Comment by zsystm** [comment]
@limengformal 
I disabled linter rule for package name at https://github.com/piplabs/story/pull/56/commits/8ec2911f3c2d70ce7f69df39253a693ae83ad821
Thanks for your opinion.

**Review by limengformal — APPROVED** [review]

**Pull request merged**
